name: papercuts
favicon: null
layout_spectrum: 0.11779634049162269
typography_spectrum: 0.6549692135304213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.11016171146184206
  lightness: 0.2423685765825212
  saturation: 0.6972157040145248
  rhythmicContrast: 0.665434361435473
purpose: []
